name: SMPClaim
version: 1.0
api-version: 1.20
author: EinfachGustaf.live
main: live.einfachgustaf.smpclaim.SMPClaim
depend:
  - WorldGuard
libraries:
  - "net.axay:kspigot:1.20.3"
  - "org.postgresql:postgresql:42.7.3"
  - "org.jetbrains.exposed:exposed-core:0.35.1"
  - "org.jetbrains.exposed:exposed-dao:0.35.1"
  - "org.jetbrains.exposed:exposed-jdbc:0.35.1"